name: Lottery Notification

on:
  schedule:
    # 每周二、四、日21:30 UTC（北京时间次日5:30）
    - cron: '0 8 * * 0,2,4'
  workflow_dispatch:  # 允许手动触发

env:
  TZ: Asia/Shanghai  # 设置时区为北京时间

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. 设置Python环境
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # 3. 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. 创建.env文件
      - name: Create environment file
        run: |
          cat << EOF > .env
          EMAIL_USER=${{ secrets.EMAIL_USER }}
          EMAIL_PASS=${{ secrets.EMAIL_PASS }}
          SMTP_SERVER=${{ secrets.SMTP_SERVER }}
          SMTP_PORT=${{ secrets.SMTP_PORT }}
          RECEIVER_EMAIL=${{ secrets.RECEIVER_EMAIL }}
          EOF

      # 5. 运行彩票检查
      - name: Run lottery check
        run: python main.py

      # 6. 上传日志(可选)
      - name: Upload logs
        if: always()  # 无论成功失败都执行
        uses: actions/upload-artifact@v4
        with:
          name: lottery-logs
          path: |
            *.log
            output.txt
